version: "2.2"
services:
  app:
    build:
      args:
        user: dealer
        uid: 1000
      context: ./config/php-fpm
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-app
    restart: always
    working_dir: /var/www/
    environment: 
      VIRTUAL_HOST: dev.studentgroup.ir
    volumes:
      - ${ROOT_DIRECTORY}:/var/www
    networks:
      - trader

  db:
    image: postgres:bullseye
    container_name: ${PROJECT_NAME}-db
    volumes:
      - db_trader:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_DB: ${MYSQL_DATABASE}
      POSTGRES_PASSWORD: example
      POSTGRES_USER: ${MYSQL_USER}
    ports:
      - '5432:5432'
    networks:
      - trader

  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    ports:
       - ${APP_PORT}:80
       - ${APP_PORT_SECURE}:443
    volumes:
      - ${ROOT_DIRECTORY}:/var/www
      - ./config/nginx:/etc/nginx/conf.d/
      - ./config/certs:/etc/nginx/certs
    networks:
      - trader
  redis:
    image: redis:alpine
    container_name: ${PROJECT_NAME}-redis
    restart: always
    networks:
      - trader
volumes:
  db_trader:
networks:
  trader:
    driver: bridge
