version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./config/php-fpm
      dockerfile: Dockerfile
    image: tilapila
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ${ROOT_DIRECTORY}:/var/www
    networks:
      - tilapila

  db:
    image: mariadb:10.4.21
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - tilapila

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
      - ${APP_PORT_SECURE}:443
    volumes:
      - ${ROOT_DIRECTORY}:/var/www
      - ./config/nginx:/etc/nginx/conf.d/
      - ./config/certs:/etc/nginx/certs
    networks:
      - tilapila

networks:
  tilapila:
    driver: bridge