version: "2.2"
services:
  app:
    build:
      args:
        user: ${WEB_USER}
        uid: ${UID}
      context: ./config/php-fpm
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ${ROOT_DIRECTORY}:/var/www
    networks:
      - ponisha

  db:
    image: mysql:8-debian
    container_name: ${PROJECT_NAME}-db
    volumes:
      - db_ponisha:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    networks:
      - ponisha

  nginx:
    image: nginx:stable
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${ROOT_DIRECTORY}:/var/www
      - ./config/nginx/:/etc/nginx/conf.d/
      - ./config/certs:/etc/nginx/certs
    networks:
      - ponisha
  redis:
    image: redis:alpine
    container_name: ${PROJECT_NAME}-redis
    restart: always
    networks:
      - ponisha
volumes:
  db_ponisha:
networks:
  ponisha:
    driver: bridge
