version: "2.2"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./config/php-fpm
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-app
    mem_limit: 1024M
    mem_reservation: 256M
    restart: unless-stopped
    working_dir: /var/www/
    environment: 
      VIRTUAL_HOST: dev.studentgroup.ir
    volumes:
      - ${ROOT_DIRECTORY}:/var/www
    networks:
      - dev

  db:
    image: mariadb:10.4.21
    mem_limit: 1024M
    mem_reservation: 256M
    container_name: ${PROJECT_NAME}-db
    restart: unless-stopped
    ports:
      - '43306:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - dev

  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-nginx
    mem_limit: 1024M
    mem_reservation: 256M
    restart: unless-stopped
    ports:
       - ${APP_PORT}:80
       - ${APP_PORT_SECURE}:443
    volumes:
      - ${ROOT_DIRECTORY}:/var/www
      - ./config/nginx:/etc/nginx/conf.d/
      - ./config/certs:/etc/nginx/certs
    networks:
      - dev
  redis:
    image: redis:alpine
    mem_limit: 1024M
    mem_reservation: 256M
    container_name: ${PROJECT_NAME}-redis
    restart: unless-stopped
    ports:
      - '46379:6379'
    networks:
      - dev
networks:
  dev:
    driver: bridge
